FROM ubuntu:xenial AS cicd-ansible
USER root

RUN apt update && \
    apt install --assume-yes software-properties-common && \
    add-apt-repository --yes --update ppa:ansible/ansible

RUN apt install --assume-yes ansible && \
    apt install --assume-yes python-docker && \
    apt install --assume-yes python-pip && \
    pip install docker-py

#ENV ANSIBLE_LOCAL_TEMP=$HOME/.ansible/tmp
#ENV ANSIBLE_REMOTE_TEMP=$HOME/.ansible/tmp