FROM ubuntu:xenial AS cicd-ansible

RUN apt update
RUN apt install --assume-yes software-properties-common
RUN add-apt-repository --yes --update ppa:ansible/ansible
RUN apt install --assume-yes ansible

ENV ANSIBLE_LOCAL_TEMP=$HOME/.ansible/tmp
ENV ANSIBLE_REMOTE_TEMP=$HOME/.ansible/tmp