FROM ubuntu:xenial
USER root

RUN apt-get update && \
  apt-get --assume-yes install software-properties-common && \
  apt-add-repository ppa:ansible/ansible && \
  apt-get --assume-yes install ansible

USER ansible